### ISSUE TITLE
fix/bug-login-back-buttton

### ISSUE THREAD

**Issue by RaulRinconX** [mobile-dev-16/flutter_app#26]
## Bug in Login Screen, Back Button Causes Unexpected Behavior After Login

There is an issue with the login screen after the user successfully logs in and navigates to the main page. When the back button is pressed, the app returns to the login screen instead of keeping the user on the main page.

### Steps to Reproduce:
1. Open the app.
2. Enter valid login credentials (e.g., admin / admin).
3. After successfully logging in, the app navigates to the main page.
4. Press the back button on the device.

### Expected Behavior:
The app should not return to the login screen after the user successfully logs in. The user should remain on the main page or be exited from the app upon pressing the back button, depending on app design.

### Actual Behavior:
The app navigates back to the login screen, even though the user is already authenticated. This may lead to confusion and disrupts the flow of the application.

### Possible Solution:
One possible solution is to remove the login screen from the navigation stack after successful login using Navigator.pushReplacement or similar methods. This ensures that pressing the back button will not return the user to the login screen.

**Comment by abelarismendy** [comment]
fixed in #25
